name: Generate Directory Tree

on:
  push:
    branches:
      - main  

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tree command
        run: sudo apt-get install -y tree

      - name: Generate directory tree
        run: tree -a > ./directory_structure.txt

      - name: Upload directory structure as artifact
        uses: actions/upload-artifact@v3
        with:
          name: directory-structure
          path: ./directory_structure.txt
